In [1]:
import numpy as np

from Imports import  *

## Applying LDA on all the features

In [2]:
X= Smarket.drop(columns= ['Year', 'Today', 'Direction'])
y= Smarket.Direction == 'Up'

In [3]:
train= Smarket.Year<2005
X_train, X_test= X.loc[train], X.loc[~train]
y_train, y_test= y.loc[train], y.loc[~train]

In [4]:
lda= LDA(store_covariance=True)
lda.fit(X_train, y_train)

LinearDiscriminantAnalysis(store_covariance=True)

In [5]:
lda.means_

array([[ 4.27902240e-02,  3.38940937e-02, -9.80651731e-03,
        -1.05987780e-02,  4.36659878e-03,  1.37184259e+00],
       [-3.95463511e-02, -3.13254438e-02,  5.83431953e-03,
         3.11045365e-03, -6.50887574e-04,  1.36320990e+00]])

In [6]:
lda.classes_

array([False,  True])

In [7]:
lda.priors_
# Prior Probability

array([0.49198397, 0.50801603])

In [8]:
lda.scalings_
# It contains the coefficients (weights) of the linear discriminants, representing the directions that maximize between-class variance while minimizing within-class variance.

array([[-0.58081056],
       [-0.49111007],
       [ 0.07707664],
       [ 0.06904095],
       [-0.04549853],
       [-1.24678716]])

In [9]:
lda_pred= lda.predict(X_test)

In [10]:
L_test= Smarket.Direction.loc[~train]
confusion_table(lda_pred, y_test)

Truth      False  True
Predicted
False         77     97
True          34     44

## Applying LDA on the least P-values features

In [11]:
X_lp= Smarket[['Lag1', 'Lag2']]

X_lp_train= X_lp.loc[train]
X_lp_test= X_lp.loc[~train]

In [12]:
lda_lp= LDA(store_covariance=True)
lda_lp.fit(X_lp_train, y_train)

LinearDiscriminantAnalysis(store_covariance=True)

In [13]:
lda_pred_lp= lda_lp.predict(X_lp_test)

In [14]:
lda_pred_lp= np.where(lda_pred_lp == True, 'Up', 'Down')

In [15]:
y_test_lp= y_test.map({True: 'Up', False: 'Down'})

In [16]:
confusion_table(lda_pred_lp, y_test_lp)

Truth      Down   Up
Predicted
Down         35   35
Up           76  106

In [17]:
lda_lp.priors_

array([0.49198397, 0.50801603])

In [18]:
lda_lp.scalings_

array([[-0.64201904],
       [-0.51352928]])

In [19]:
lda_lp.means_

array([[ 0.04279022,  0.03389409],
       [-0.03954635, -0.03132544]])

In [20]:
lda_lp.classes_

array([False,  True])

In [23]:
lda_prob_lp= lda_lp.predict_proba(X_lp_test)
np.all(np.where(lda_prob_lp[:,1] >= 0.5, 'Up', 'Down') == lda_pred_lp)

np.True_

In [25]:
np.sum(lda_prob_lp[:,0] > 0.9)

np.int64(0)

In [27]:
np.mean(lda_pred_lp==y_test_lp)

np.float64(0.5595238095238095)