In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from ISLP import load_data
import seaborn as sns
import statsmodels.api as sm
from ISLP.models import summarize
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
rng = np.random.default_rng(1)
x = rng.normal(size=100)
y = 2 * x + rng.normal(size=100)

## Regressing X onto y (without Intercept)

In [3]:
from ISLP.models import ModelSpec as MS
x = pd.DataFrame({'X':x})
y = pd.DataFrame({'Y':y})
design = MS('X', intercept=False)
X = design.fit_transform(x)
model_X_onto_y = sm.OLS(y,X).fit()
summarize(model_X_onto_y)

     coef  std err       t  P>|t|
X  1.9762    0.117  16.898    0.0

## Regressing y onto X (without Intercept)

In [4]:
design1 = MS(['Y'], intercept=False)
y = design1.fit_transform(y)
model_y_onto_X = sm.OLS(X,y).fit()
summarize(model_y_onto_X)

     coef  std err       t  P>|t|
Y  0.3757    0.022  16.898    0.0

In [5]:
num=0;den=0
for i in range(0,len(X)):
    num= num + (X['X'].iloc[i]*y['Y'].iloc[i])
    den= den + np.square(X['X'].iloc[i])

beta_cap_of_Y_onto_X = num/den
beta_cap_of_Y_onto_X

np.float64(1.9762423774420508)

In [6]:
num1=0; den1=0
for i in range(0,len(X)):
    num1 = num1 + np.square((y['Y'].iloc[i] - (X['X'].iloc[i]*beta_cap_of_Y_onto_X)))
    den1 = den1 + np.square(X['X'].iloc[i])
den1= (len(X)-1)*den1

std_error_of_beta_cap_of_Y_onto_X = np.sqrt(num1/den1)
std_error_of_beta_cap_of_Y_onto_X

np.float64(0.11694837274226327)

In [7]:
t_stats_Y_onto_X = beta_cap_of_Y_onto_X/std_error_of_beta_cap_of_Y_onto_X
t_stats_Y_onto_X

np.float64(16.8984170630351)

## Regressing X onto y (using Intercept)

In [8]:
design2 = MS('X')
X_dummy = design2.fit_transform(x)
model_X_onto_y_using_intercept = sm.OLS(y,X_dummy).fit()
summarize(model_X_onto_y_using_intercept)

             coef  std err       t  P>|t|
intercept -0.0760    0.101  -0.756  0.451
X          1.9686    0.118  16.734  0.000

## Regressing y onto X (using Intercept)

In [9]:
design3 = MS(['Y'])
y_dummy = design3.fit_transform(y)
model_y_onto_X_using_intercept = sm.OLS(X,y_dummy).fit()
summarize(model_y_onto_X_using_intercept)

             coef  std err       t  P>|t|
intercept  0.0095    0.044   0.216  0.829
Y          0.3763    0.022  16.734  0.000