In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ISLP
from ISLP import load_data
from ISLP.models import ModelSpec as MS, summarize
import statsmodels.api as sm

In [2]:
boston = load_data("boston")

In [3]:
boston.head(5)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,5.33,36.2

In [4]:
y= boston["crim"]
X = boston.drop(columns='crim')
X.insert(0,'constant',1)

In [5]:
X.head()

,constant,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat,medv
0,1,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,4.98,24.0
1,1,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,9.14,21.6
2,1,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,4.03,34.7
3,1,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,2.94,33.4
4,1,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,5.33,36.2

In [6]:
y.head()

0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
Name: crim, dtype: float64

In [7]:
X.columns

Index(['constant', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad',
       'tax', 'ptratio', 'lstat', 'medv'],
      dtype='object')

In [8]:
len(X.columns)

13

In [42]:
model_1 = sm.OLS(y,X[['constant','zn']]).fit()
model_2 = sm.OLS(y,X[['constant','indus']]).fit()
model_3 = sm.OLS(y,X[['constant','chas']]).fit()
model_4 = sm.OLS(y,X[['constant','nox']]).fit()
model_5 = sm.OLS(y,X[['constant','rm']]).fit()
model_6 = sm.OLS(y,X[['constant','age']]).fit()
model_7 = sm.OLS(y,X[['constant','dis']]).fit()
model_8 = sm.OLS(y,X[['constant','rad']]).fit()
model_9 = sm.OLS(y,X[['constant','tax']]).fit()
model_10 = sm.OLS(y,X[['constant','ptratio']]).fit()
model_11 = sm.OLS(y,X[['constant','lstat']]).fit()
model_12 = sm.OLS(y,X[['constant','medv']]).fit()

In [43]:
summarize(model_1)

            coef  std err       t  P>|t|
constant  4.4537    0.417  10.675    0.0
zn       -0.0739    0.016  -4.594    0.0

In [44]:
summarize(model_2)

            coef  std err      t  P>|t|
constant -2.0637    0.667 -3.093  0.002
indus     0.5098    0.051  9.991  0.000

In [45]:
summarize(model_3)

            coef  std err      t  P>|t|
constant  3.7444    0.396  9.453  0.000
chas     -1.8928    1.506 -1.257  0.209

## 'chas',

In [46]:
summarize(model_4)

             coef  std err       t  P>|t|
constant -13.7199    1.699  -8.073    0.0
nox       31.2485    2.999  10.419    0.0

In [47]:
summarize(model_5)

             coef  std err      t  P>|t|
constant  20.4818    3.364  6.088    0.0
rm        -2.6841    0.532 -5.045    0.0

In [48]:
summarize(model_5)

             coef  std err      t  P>|t|
constant  20.4818    3.364  6.088    0.0
rm        -2.6841    0.532 -5.045    0.0

In [49]:
summarize(model_6)

            coef  std err      t  P>|t|
constant -3.7779    0.944 -4.002    0.0
age       0.1078    0.013  8.463    0.0

In [50]:
summarize(model_7)

            coef  std err       t  P>|t|
constant  9.4993    0.730  13.006    0.0
dis      -1.5509    0.168  -9.213    0.0

In [51]:
summarize(model_8)

            coef  std err       t  P>|t|
constant -2.2872    0.443  -5.157    0.0
rad       0.6179    0.034  17.998    0.0

In [52]:
summarize(model_9)

            coef  std err       t  P>|t|
constant -8.5284    0.816 -10.454    0.0
tax       0.0297    0.002  16.099    0.0

In [53]:
summarize(model_10)

             coef  std err      t  P>|t|
constant -17.6469    3.147 -5.607    0.0
ptratio    1.1520    0.169  6.801    0.0

In [54]:
summarize(model_11)

            coef  std err       t  P>|t|
constant -3.3305    0.694  -4.801    0.0
lstat     0.5488    0.048  11.491    0.0

In [55]:
summarize(model_12)

             coef  std err       t  P>|t|
constant  11.7965    0.934  12.628    0.0
medv      -0.3632    0.038  -9.460    0.0

## Multiple regressed

In [40]:
model_for_all_pred = sm.OLS(y,X).fit()

In [41]:
summarize(model_for_all_pred)

             coef  std err      t  P>|t|
constant  13.7784    7.082  1.946  0.052
zn         0.0457    0.019  2.433  0.015
indus     -0.0584    0.084 -0.698  0.486
chas      -0.8254    1.183 -0.697  0.486
nox       -9.9576    5.290 -1.882  0.060
rm         0.6289    0.607  1.036  0.301
age       -0.0008    0.018 -0.047  0.962
dis       -1.0122    0.282 -3.584  0.000
rad        0.6125    0.088  6.997  0.000
tax       -0.0038    0.005 -0.730  0.466
ptratio   -0.3041    0.186 -1.632  0.103
lstat      0.1388    0.076  1.833  0.067
medv      -0.2201    0.060 -3.678  0.000

In [56]:
X_unvariate = pd.DataFrame({"Individual_coeff":[model_1.params[1], model_2.params[1], model_3.params[1], model_4.params[1], model_5.params[1], model_6.params[1], model_7.params[1], model_8.params[1], model_9.params[1], model_10.params[1], model_11.params[1],model_12.params[1]]})

C:\Users\AAYUSH OJHA\AppData\Local\Temp\ipykernel_13148\441444300.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X_unvariate = pd.DataFrame({"Individual_coeff":[model_1.params[1], model_2.params[1], model_3.params[1], model_4.params[1], model_5.params[1], model_6.params[1], model_7.params[1], model_8.params[1], model_9.params[1], model_10.params[1], model_11.params[1],model_12.params[1]]})

In [59]:
X_bivariate = pd.DataFrame({"Multiple_regressed_coeff":model_for_all_pred.params})

In [68]:
X_bivariate.drop('constant',inplace=True)